name: Test with Coverage

on:
  push:
    branches: [ main, dev, zm/tests ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          cmake \
          qt6-base-dev \
          qt6-declarative-dev \
          qt6-tools-dev \
          qt6-tools-dev-tools \
          qml6-module-qtquick \
          qml6-module-qtquick-controls \
          qml6-module-qtquick-layouts \
          qml6-module-qtqml-workerscript \
          qml6-module-qt-labs-platform \
          qml6-module-qtquick-window \
          qml6-module-qtquick-templates \
          libgtest-dev \
          libgmock-dev \
          libzmq3-dev \
          wget \
          lcov
        # Download ZeroMQ C++ header (not provided by libzmq3-dev)
        sudo wget -O /usr/include/zmq.hpp https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp

    - name: Build and Test
      run: |
        cd ClusterDisplay
        mkdir -p build
        cd build
        cmake .. -DCODE_COVERAGE=ON
        make
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        cd ClusterDisplay/build
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./ClusterDisplay/build/coverage.info
        fail_ci_if_error: true
